Gradlew: refactored.

diff --git a/services/bookmarks/gradlew b/services/bookmarks/gradlew
--- a/services/bookmarks/gradlew
+++ b/services/bookmarks/gradlew
@@ -3,38 +3,70 @@ GRADLE_CONTAINER=${GRADLE_CONTAINER:-gradled}
 GRADLE_USER_HOME=${GRADLE_USER_HOME:-~/.gradle}
 GRADLE_VERSION=${GRADLE_VERSION:-6.0.1-jdk8}
 
-# Look for existing daemon, create if required.
-cid=`docker container ls -aqf name=$GRADLE_CONTAINER`
-if [ -z $cid ]; then
-	echo -n "Starting $GRADLE_CONTAINER container... "
+docker_machine_ssh() {
+    [ -x "$(which docker-machine 2>/dev/null)" ] \
+        && echo "docker-machine ssh `docker-machine active` -- " \
+        || echo ""
+}
 
-	# System paths (docker-machine compatibility)
-	DOCKER_MACHINE_SSH=$([ -x "$(which docker-machine 2>/dev/null)" ] && echo "docker-machine ssh `docker-machine active` -- " || echo "")
-	DOCKER_BIN="$($DOCKER_MACHINE_SSH which docker)"
-	DOCKER_COMPOSE_BIN="$($DOCKER_MACHINE_SSH which docker-compose)"
+git_describe() {
+    git describe --always --first-parent
+}
 
-	docker run \
-		--detach \
-		--init \
-		--name $GRADLE_CONTAINER \
-		--rm \
-		--tmpfs /home/gradle/.gradle/daemon \
-		--user gradle:100 \
-		--volume "$GRADLE_USER_HOME":/home/gradle/.gradle \
-		--volume "$PWD":/home/gradle/project \
-		--volume "$DOCKER_BIN":/usr/bin/docker \
-		--volume "$DOCKER_COMPOSE_BIN":/usr/bin/docker-compose \
-		--volume /var/run/docker.sock:/var/run/docker.sock \
-		--workdir /home/gradle/project \
-		gradle:$GRADLE_VERSION \
-		tail -f /dev/null
-else
-	echo "Re-using $GRADLE_CONTAINER container $cid..."
-fi
+git_dirty() {
+    git diff HEAD \
+        | xargs -r -d '\n' bash -c 'echo "$@" \
+            | sha1sum \
+            | cut -c -7 \
+            | cat <(echo -n '.dirty-') - '
+}
 
-# Hack in the project version
-gitDescribe=`git describe --always --first-parent`
-gitDirty=`git diff HEAD | xargs -r -d'\n' bash -c 'echo "$@" | sha1sum | cut -c -7 | cat <(echo -n '.dirty-') -'`
+gradle_cmd() {
+    docker exec $GRADLE_CONTAINER gradle "$@" -Pversion="$(git_describe)$(git_dirty)"
+}
 
-# Run gradle command
-docker exec $GRADLE_CONTAINER gradle $@ -Pversion="$gitDescribe$gitDirty"
+gradle_daemon() {
+    local docker_machine_ssh="$(docker_machine_ssh)"
+    local docker_bin="$($docker_machine_ssh which docker)"
+    local compose_bin="$($docker_machine_ssh which docker-compose)"
+
+    docker run \
+        --detach \
+        --init \
+        --name $GRADLE_CONTAINER \
+        --rm \
+        --tmpfs /home/gradle/.gradle/daemon \
+        --user gradle:100 \
+        --volume "$GRADLE_USER_HOME":/home/gradle/.gradle \
+        --volume "$PWD":/home/gradle/project \
+        --volume "$docker_bin":/usr/bin/docker \
+        --volume "$compose_bin":/usr/bin/docker-compose \
+        --volume /var/run/docker.sock:/var/run/docker.sock \
+        --workdir /home/gradle/project \
+        gradle:$GRADLE_VERSION \
+        tail -f /dev/null
+}
+
+gradle_daemon_cid() {
+    docker container ls -aqf name=$GRADLE_CONTAINER
+}
+
+main() {
+    echo -n "Finding $GRADLE_CONTAINER container... "
+
+    # Start Gradle Daemon (if necessary)
+    local cid="$(gradle_daemon_cid)"
+    if [ -z $cid ]; then
+        echo "not found."
+        echo -n "Starting $GRADLE_CONTAINER container... "
+        gradle_daemon >/dev/null
+        gradle_daemon_cid
+    else
+        echo "found $cid."
+    fi
+
+    # Run Gradle command
+    gradle_cmd "$@"
+}
+
+main "$@"
